export const CREATE_FRUIT_LISTEN = 'dashboard/CREATE_FRUIT_LISTEN'
export const CREATE_FRUIT_SUCCESS = 'dashboard/CREATE_FRUIT_SUCCESS'

export const HANDLE_CREATE_FRUIT_LOADER = 'dashboard/HANDLE_CREATE_FRUIT_LOADER'
